language: go

go: 1.7.5

go_import_path: github.com/next-stack/kubernetes-github-auth

before_install:
  - go get github.com/Masterminds/glide

install:
  - glide install
  - go install

script:
  - make build
